export default {
  SEARCH_MEDIA: 'SEARCH_MEDIA',
  ADD_SAVED: 'ADD_SAVED',
  REMOVE_SAVED: 'REMOVE_SAVED',
  SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
  VISIBILITY_FILTERS: {
    SHOW_ALL: 'SHOW_ALL',
    SHOW_COMPLETED: 'SHOW_COMPLETED',
    SHOW_ACTIVE: 'SHOW_ACTIVE'
  },
  API_ROOT: 'http://www.omdbapi.com/?apikey=49efaa37',
}